### ISSUE TITLE
Order 1090-5438 is missing an On-Off Switch

### ISSUE THREAD

**Issue by jasonliu125** [LArkema/dctransistor-project#2]
I hope you're doing well! My board appears to be missing an on off switch. I see the outline for where it's supposed to be but I cannot turn the board on. Would you be able to send a replacement or exchange this? Image attached.
![346111151_1247028495933527_6184488625220488240_n](https://github.com/LArkema/dctransistor-project/assets/63115116/a88de5fc-8713-422a-911b-cfae418bd4e4)

**Comment by LArkema** [comment]
Hello,

GitHub issues are meant for bugs and improvements with the software or project files. Individual board problems should be addressed via email to support@dctransistor.com or other DCTransistor email address to resolve individual issues. Please see email correspondence for this order. 

Thank you for understanding, but this issue will be deleted in order to keep the repo focused on the open source project.
